name: Build
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    name:    build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
