name: Release
on:
  push:
    tags:
      - 'version-*'

jobs:
  release:
    runs-on: ubuntu-latest
    name:    release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make
        run:  make
      - name: install_aws
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
      - name: push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PUSHUSER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PUSHSECRET }}
          AWS_DEFAULT_REGION: us-west-2
          DBUILDER: ${{ secrets.DBUILDER }}
          DPASS:    ${{ secrets.DPASS }}
        run: export AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION DBUILDER DPASS && make push 
